// AUTO-GENERATED by tools/generate_protocol_stubs.py. DO NOT EDIT.
#pragma once

#include <array>
#include <string_view>

namespace pre_buddy {

constexpr std::array<std::string_view, 22> kGeneratedEventKinds = {
    "pre.system.wake_word",
    "pre.bg_agents.change",
    "pre.router.decision",
    "pre.confidence.warning",
    "pre.confidence.snapshot",
    "pre.kg.delta",
    "pre.training.progress",
    "pre.scheduler.upcoming",
    "pre.tools.rollup",
    "pre.system.memory_write",
    "pre.system.proximity",
    "pre.system.error",
    "pre.character.set",
    "pre.audio.wake_word_detected",
    "pre.audio.input_start",
    "pre.audio.input_frame",
    "pre.audio.input_stop",
    "pre.audio.output_start",
    "pre.audio.output_frame",
    "pre.audio.output_stop",
    "pre.audio.codec",
    "pre.audio.error",
};

} // namespace pre_buddy
