#!/usr/bin/env python3
"""Generate protocol stubs from shared/protocol/events.yaml.

Outputs:
- server/pre_buddy/generated_event_kinds.py
- firmware/core/include/pre_buddy/generated_event_kinds.h

Use --check in CI to ensure generated files are up-to-date.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "shared/protocol/events.yaml"
PY_OUT = ROOT / "server/pre_buddy/generated_event_kinds.py"
CPP_OUT = ROOT / "firmware/core/include/pre_buddy/generated_event_kinds.h"


@dataclass
class EventDef:
    name: str
    direction: str


def parse_schema(text: str) -> list[EventDef]:
    events: list[EventDef] = []
    in_events = False
    current: dict[str, str] | None = None

    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue

        if line.strip() == "events:":
            in_events = True
            continue

        if not in_events:
            continue

        stripped = line.lstrip()
        if stripped.startswith("- "):
            if current:
                events.append(EventDef(name=current["name"], direction=current["direction"]))
            current = {}
            payload = stripped[2:]
            if payload.startswith("name:"):
                current["name"] = payload.split(":", 1)[1].strip()
            continue

        if current is None:
            continue

        if ":" in stripped:
            key, value = stripped.split(":", 1)
            current[key.strip()] = value.strip()

    if current:
        events.append(EventDef(name=current["name"], direction=current["direction"]))

    if not events:
        raise ValueError("no events parsed from schema")

    for ev in events:
        if not ev.name.startswith("pre."):
            raise ValueError(f"event must start with pre.: {ev.name}")
        if not ev.direction:
            raise ValueError(f"missing direction for {ev.name}")

    return events


def render_python(events: list[EventDef]) -> str:
    names = ",\n    ".join(f'"{e.name}"' for e in events)
    return f'''"""AUTO-GENERATED by tools/generate_protocol_stubs.py. DO NOT EDIT."""

from __future__ import annotations

EVENT_KIND_NAMES: tuple[str, ...] = (
    {names},
)

EVENT_DIRECTIONS: dict[str, str] = {{
{chr(10).join(f'    "{e.name}": "{e.direction}",' for e in events)}
}}
'''


def render_cpp(events: list[EventDef]) -> str:
    names = "\n".join(f'    "{e.name}",' for e in events)
    return f'''// AUTO-GENERATED by tools/generate_protocol_stubs.py. DO NOT EDIT.
#pragma once

#include <array>
#include <string_view>

namespace pre_buddy {{

constexpr std::array<std::string_view, {len(events)}> kGeneratedEventKinds = {{
{names}
}};

}} // namespace pre_buddy
'''


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists():
            return False
        return path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args(argv)

    events = parse_schema(SCHEMA.read_text(encoding="utf-8"))
    py = render_python(events)
    cpp = render_cpp(events)

    ok_py = write_or_check(PY_OUT, py, args.check)
    ok_cpp = write_or_check(CPP_OUT, cpp, args.check)

    if args.check and not (ok_py and ok_cpp):
        print("generated files are stale; run tools/generate_protocol_stubs.py", file=sys.stderr)
        return 1

    if not args.check:
        print(f"generated {PY_OUT.relative_to(ROOT)} and {CPP_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
