#!/usr/bin/env python3
"""Convert the rendered sprite PNGs into a C++ header of RGB565 arrays.

Output: ``firmware/esp32/main/sprites_data.h`` (auto-generated). The
ESP32 build includes this once at link time; the rest of the firmware
references sprites by index via ``sprite_atlas.h``.

Run after ``generate_sprites.py``:

    python3 tools/generate_sprites.py
    python3 tools/sprites_to_header.py
"""

from __future__ import annotations

from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:  # pragma: no cover - dev-only script
    raise SystemExit(
        "sprites_to_header.py needs Pillow installed: pip install Pillow"
    ) from exc


SPRITE_DIR = (Path(__file__).resolve().parent.parent
              / "firmware" / "esp32" / "main" / "sprites")
HEADER_PATH = (Path(__file__).resolve().parent.parent
               / "firmware" / "esp32" / "main" / "sprites_data.h")

# Generator MUST emit sprites in the same order as sprite_atlas.h's
# sprite_index() function: 8 expressions per character, characters in
# Sage / Sprout / Sentinel order.
CHARACTERS = ("sage", "sprout", "sentinel")
EXPRESSIONS = (
    "neutral", "surprised", "thinking", "concerned",
    "happy", "sleepy", "curious", "error",
)


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def emit_sprite_array(img: Image.Image, name: str, out_lines: list[str]) -> None:
    width, height = img.size
    pixels = list(img.convert("RGB").getdata())
    out_lines.append(
        f"inline constexpr std::uint16_t {name}[{height} * {width}] = {{"
    )
    row = []
    for idx, (r, g, b) in enumerate(pixels):
        row.append(f"0x{rgb888_to_rgb565(r, g, b):04x}")
        if (idx + 1) % 12 == 0:
            out_lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        out_lines.append("    " + ", ".join(row) + ",")
    out_lines.append("};")
    out_lines.append("")


def main() -> int:
    if not SPRITE_DIR.exists():
        print(f"sprites_to_header.py: {SPRITE_DIR} missing — run generate_sprites.py first")
        return 1

    lines: list[str] = []
    lines.append("// SPDX-License-Identifier: TBD")
    lines.append("// PRE Buddy — generated sprite atlas (RGB565).")
    lines.append("//")
    lines.append("// Auto-generated by tools/sprites_to_header.py. Do not edit by hand.")
    lines.append("// Order matches firmware/core/include/pre_buddy/sprite_atlas.h::sprite_index().")
    lines.append("// Storage: ~370 KB total (24 sprites × 96×80 × 2 bytes), comfortably")
    lines.append("// inside the CoreS3 16 MB flash budget.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace pre_buddy::sprites {")
    lines.append("")

    refs: list[str] = []
    for character in CHARACTERS:
        for expression in EXPRESSIONS:
            path = SPRITE_DIR / f"{character}_{expression}.png"
            if not path.exists():
                print(f"missing sprite: {path}")
                return 1
            arr_name = f"_sprite_{character}_{expression}"
            with Image.open(path) as img:
                emit_sprite_array(img, arr_name, lines)
            refs.append(arr_name)

    # Flat index → pointer table. Order matches sprite_index().
    lines.append("inline constexpr const std::uint16_t* SPRITE_TABLE[24] = {")
    for ref in refs:
        lines.append(f"    {ref},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace pre_buddy::sprites")
    lines.append("")

    HEADER_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {HEADER_PATH} ({len(refs)} sprites)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
