"""AUTO-GENERATED by tools/generate_protocol_stubs.py. DO NOT EDIT."""

from __future__ import annotations

EVENT_KIND_NAMES: tuple[str, ...] = (
    "pre.system.wake_word",
    "pre.bg_agents.change",
    "pre.router.decision",
    "pre.confidence.warning",
    "pre.confidence.snapshot",
    "pre.kg.delta",
    "pre.training.progress",
    "pre.scheduler.upcoming",
    "pre.tools.rollup",
    "pre.system.memory_write",
    "pre.system.proximity",
    "pre.system.error",
    "pre.character.set",
)

EVENT_DIRECTIONS: dict[str, str] = {
    "pre.system.wake_word": "bidirectional",
    "pre.bg_agents.change": "server_to_device",
    "pre.router.decision": "server_to_device",
    "pre.confidence.warning": "server_to_device",
    "pre.confidence.snapshot": "server_to_device",
    "pre.kg.delta": "server_to_device",
    "pre.training.progress": "server_to_device",
    "pre.scheduler.upcoming": "server_to_device",
    "pre.tools.rollup": "server_to_device",
    "pre.system.memory_write": "server_to_device",
    "pre.system.proximity": "bidirectional",
    "pre.system.error": "bidirectional",
    "pre.character.set": "bidirectional",
}
